name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Proof HTML
        uses: anishathalye/proof-html@v1.2.0
        with:
          directory: ./public_html
          check_html: true
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "task5-bootstrap"
          heroku_email: "direva99@gmail.com"
