name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Proof HTML
        uses: anishathalye/proof-html@v1.2.0
        with:
          directory: ./public_html
          check_html: true
